CS2103JAN2018-W13-B1/main

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/model/tag/UniqueTagList.java
- src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/testutil/TypicalTags.java
Added removeTag() method to Model API.
Function: Removes an existing tag from all persons in address book containing the given tag.
However, this function cannot be called yet as it needs to be implemented in the Logic Component.
> Week 7 Enhancement Model Component

- README.adoc
- docs/DeveloperGuide.adoc
Updated links to badges in the README. 
[also need to change project name]
> Week 7: Updated README

- docs/DeveloperGuide.adoc
Added more user stories and glossary terms
> Week 7: User Stories, Glossary

- docs/DeveloperGuide.adoc
Added more Use Cases in the Developer Guide.
> Week 7: Use Cases 

- docs/DeveloperGuide.adoc
Edited DeveloperGuide.adoc to include new Target User Profile, Value proposition and added more NFRs.
> Week 7: Target User Profile, Value Proposition, NFR

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/test/java/guitests/guihandles/PersonCardHandle.java
- src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
add colours to tag labels and the tests
> Week 7 Enhancement UI Component

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/test/java/guitests/guihandles/PersonCardHandle.java
- src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Reverts CS2103JAN2018-W13-B1/main#39
> Revert "Week 7 Enhancement UI Component"

- docs/UserGuide.adoc
> Updated UserGuide 

- README.adoc
Things done:
- short introduction added
- main features section added
Things that still need to be done:
- UI mockup
- marketing blurb
> Updated README [Work In Progress]

- docs/DeveloperGuide.adoc
- added release notes for features in User Stories
- added short summary for target profile
- corrected NFRS
> Updated DeveloperGuide

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/FindTagCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
- src/main/java/seedu/address/model/person/TagsContainKeywordsPredicate.java
- src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
- src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
- src/test/java/seedu/address/model/person/TagsContainKeywordsPredicateTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Created a new command called FindTagCommand that shows a list of persons who contain tags that match any of the given keywords. Matching of tag names to keywords is case-insensitive.
Corresponds to Issue #21.
> V1.1: Find by tag enhancement

- docs/UserGuide.adoc
- information added for orderadd, orderedit, and orderdelete commands
> V1.2: Updated User Guide for OrderCommands

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
- src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
- src/main/java/seedu/address/logic/commands/FindGroupCommand.java
- src/main/java/seedu/address/logic/commands/FindPreferenceCommand.java
Just a small update to change command word and alias for finding and deleting group and preferences commands.
> Changed Command Word for group and preference related commands

- docs/UserGuide.adoc
- src/main/java/seedu/address/commons/core/GuiSettings.java
- src/main/java/seedu/address/commons/events/ui/ChangeThemeEvent.java
- src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
- src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/model/theme/Theme.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/LightTheme.css
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
- src/test/java/seedu/address/model/theme/ThemeTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
> V1.3: Change themes

- src/test/java/seedu/address/testutil/TypicalGroups.java
- src/test/java/systemtests/DeleteGroupCommandSystemTest.java
- src/test/java/systemtests/DeleteOrderCommandSystemTest.java
- src/test/java/systemtests/DeletePreferenceCommandSystemTest.java
- src/test/java/systemtests/FindGroupCommandSystemTest.java
- src/test/java/systemtests/FindPreferenceCommandSystemTest.java
As stated in title, plus fixing certain tests in FindGroup and FindPreference System Tests due to change in command words.
> System Tests for Delete Group and Delete Preference.

- src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/EditOrderCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/EditOrderCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/order/UniqueOrderList.java
- src/main/java/seedu/address/ui/OrderCard.java
- src/test/java/guitests/guihandles/OrderCardHandle.java
- src/test/java/guitests/guihandles/OrderListPanelHandle.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditOrderCommandParserTest.java
- src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
- src/test/java/seedu/address/ui/OrderCardTest.java
- src/test/java/seedu/address/ui/OrderListPanelTest.java
- src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
- src/test/java/systemtests/EditOrderCommandSystemTest.java
- Edit orders
- More JUnit tests
> V1.3: Edit Orders

- docs/UserGuide.adoc
- added information about newly implemented commands
- added some sample `coming in v2.0` commands
> V1.4: Updated UserGuide

- src/main/resources/view/DarkTheme.css
Made empty cells of list view transparent.
> Fix ListView components in Ui displaying empty cells.

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
Updated UserGuide.
Added missing command in CommandSyntaxListUtil.java
> Updated UserGuide [Alicia]

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/java/seedu/address/ui/PersonPanel.java
- src/main/resources/view/HelpWindow.fxml
> V1.4.1: Fixed HelpWindow bug

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/LightTheme.css
- updates `LightTheme.css` to make it consistent with `DarkTheme.css`
> Bug Fix: Updated LightTheme

- docs/UserGuide.adoc
Categorized commands into sections.
Revamped the Command Summary section.
We still need to update the following sections:
- ContactSails UI (will contain a screenshot marked up with what each panel is)
- Glossary (see comment in UserGuide.adoc to see what terms need to be defined)
> Documentation Fix: UserGuide

- src/main/java/seedu/address/logic/commands/AddEntryCommand.java
> Fixed AddEntry Command Example

- src/main/resources/view/CalendarPanel.fxml
- src/main/resources/view/CentrePanel.fxml
- src/main/resources/view/MainWindow.fxml
> Fix for Default centre panel size

- src/main/java/seedu/address/commons/events/ui/ResetPersonPanelEvent.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/UndoableCommand.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/ui/CentrePanel.java
- src/main/java/seedu/address/ui/PersonPanel.java
> Fix Person Panel not updating information when Undo/Redo/Clear is executed.

- collated/functional/AJZ1995.md
- collated/functional/SuxianAlicia-reused.md
- collated/functional/SuxianAlicia.md
- collated/functional/amad-person.md
- collated/test/AJZ1995.md
- collated/test/SuxianAlicia.md
- collated/test/amad-person.md
- docs/AboutUs.adoc
- docs/UserGuide.adoc
- docs/team/aadyaamaddi.adoc
- added Project Portfolio
- rebuilt collated files to include new annotations
> Project Portfolio Page [Aadyaa]

- docs/UserGuide.adoc
Glossary in UG has terms added.
> Added Glossary to UserGuide 

- src/main/java/seedu/address/logic/commands/EditOrderCommand.java
- src/main/java/seedu/address/logic/parser/ChangeOrderStatusCommandParser.java
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/commands/ChangeOrderStatusCommandTest.java
- src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
- src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ChangeOrderStatusCommandParserTest.java
- src/test/java/seedu/address/model/order/DeliveryDateTest.java
- src/test/java/seedu/address/model/order/OrderInformationTest.java
- src/test/java/seedu/address/model/order/OrderStatusTest.java
- src/test/java/seedu/address/model/order/PriceTest.java
- src/test/java/seedu/address/model/order/QuantityTest.java
- src/test/java/systemtests/EditOrderCommandSystemTest.java
Refactoring existing tests and adding tests for untested commands.
Will be updating/refining tests again in another PR.
> Orders: Tests
